### PR TITLE
UI Search page alignment

### PR DESCRIPTION
**Pull request by hgupta-tna**

### CODE REVIEW

**Comment by hgupta-tna** [comment]
Search

**Comment by AndrewBewseyTNA** [comment]
Approved having seen it live!

**Comment by mark-bell-tna** [comment]
This is a big improvement. How much work would it be to make the OHOS results look the same as the Discovery ones? i.e. with a box around them, and the expansion arrow if that does anything (?).

**Comment by hgupta-tna** [comment]
Not much. Me and Andrew discussed about putting the OHOS title into box and putting some information there. But given that we don't have any other data, if we put it in here in the box, then either there won't be anything to put in the next page or it will redundant.

**Review by mark-bell-tna — APPROVED** [review]
This looks much better than the previous interface. In the interests of consistency it would be nice to have borders drawn around the OHOS entries too, however, I understand the reasons for not doing it yet. When we have more data to display with the entries, beyond title, the borders should be added in.

**Pull request merged**
